<?php

/**
 * @file
 * Integration ueditor for wysiwyg.
 */

/**
 * Implementation of hook_init().
 */
function ueditor_init() {
	if(module_exists('libraries')){
		$lib_path = libraries_get_path('ueditor');
		drupal_add_css($lib_path . '/themes/default/css/ueditor.css');
	}
  drupal_add_js(drupal_get_path('module', 'ueditor') . '/js/ueditor.toolbars.js');
}

/**
 * Implements hook_permission().
 */
function ueditor_permission() {
  $perms['upload file with ueditor'] = array(
    'title' => t('Upload file with ueditor'),
  );

	return $perms;
}

/**
 * Implements hook_menu().
 */
function ueditor_menu() {
	$items['ueditor/controller'] = array(		
		'title' => 'Ueditor Control',
    'page callback' => '_ueditor_controller',		
    'access arguments' => array('upload file with ueditor'),
		'type' => MENU_CALLBACK,
	);

  return $items  ; 
}

/**
 * Implements hook_wysiwyg_include_directory().
 */
function ueditor_wysiwyg_include_directory($type) {
  switch ($type) {
    case 'editors':
      return $type;
  }
}

/**
 * The main entrance of ueditor command.
 */
function _ueditor_controller() {
	//header('Access-Control-Allow-Origin: http://www.baidu.com'); //Set http://www.baidu.com allow cross-domain access
	//header('Access-Control-Allow-Headers: X-Requested-With,X_Requested_With'); //Settings allow cross-domain header
	date_default_timezone_set("Asia/Chongqing");
	error_reporting(E_ERROR);
	header("Content-Type: text/html; charset=utf-8");
	
	$file_path = strtr(DRUPAL_ROOT,'\\','/') . '/' . drupal_get_path('module', 'ueditor');
	$CONFIG = drupal_json_decode(preg_replace("/\/\*[\s\S]+?\*\//", "", file_get_contents($file_path . '/includes/config.json')), true);
	$ueditor_uploadpath_config = variable_get('ueditor_uploadpath_config');

	foreach($ueditor_uploadpath_config as $key => $pathitem){
		if(isset($CONFIG[$key])){
			$CONFIG[$key] = _ueditor_realpath($pathitem);
		}
	}

	$action = $_GET['action'];

	switch ($action) {
			case 'config':
					$result =  json_encode($CONFIG);
					break;

			/* upload image */
			case 'uploadimage':
			/* upload scrawl */
			case 'uploadscrawl':
			/* upload video */
			case 'uploadvideo':
			/* upload file */
			case 'uploadfile':
					$result = include($file_path. '/includes/action_upload.php');
					break;

			/* list image */
			case 'listimage':
					$result = include($file_path. '/includes/action_list.php');
					break;
			/* list file */
			case 'listfile':
					$result = include($file_path. '/includes/action_list.php');
					break;

			/* catch image */
			case 'catchimage':
					$result = include($file_path. '/includes/action_crawler.php');
					break;

			default:
					$result = json_encode(array(
							'state'=> t('Request address error')
					));
					break;
	}

	/* output */
	if (isset($_GET["callback"])) {
			if (preg_match("/^[\w_]+$/", $_GET["callback"])) {
					echo htmlspecialchars($_GET["callback"]) . '(' . $result . ')';
			} else {
					echo json_encode(array(
							'state'=> t('callback parameters are not legitimate')
					));
			}
	} else {
			echo $result;
	}
}

/**
 * Change %path to realpath.
 */
function _ueditor_realpath($path, $auto=FALSE) {
  global $user;
  $lib_path = 'sites/all/libraries';
  $mod_path = drupal_get_path('module', 'ueditor');
  $path = strtr($path,
    array(
      '%b' => base_path(),
      '%m' => $mod_path,
      '%l' => $lib_path,
      '%f' => variable_get('file_public_path', conf_path() . '/files'),
      '%d' => strtr(DRUPAL_ROOT,'\\','/'),
      '%u' => $user->uid,
    )
  );
  $path = strtr($path, '\\', '/');
  if($auto) $path .= '/';
  $path = str_replace('//', '/', $path);
  return $path;
}
